### ISSUE TITLE
Replacing the concrete5 5.6 repo with the current 5.7

### ISSUE THREAD

**Issue by KorvinSzanto** [concrete5/concrete5-legacy#1906]
We need to rip this bandaid off at some point, https://github.com/concrete5/concrete5 should be the most recent most active concrete5 front end which is 5.7. So then we should move this repo to something different like https://github.com/concrete5/concrete5-legacy or https://github.com/concrete5/concrete5.6

Thoughts?

**Comment by fmaruna** [comment]
yup. I think https://github.com/concrete5/concrete5-legacy  is more clear, and i agree with your thoughts last night, we'd save ourselves a lot of pain by trying to talk more like "concrete5, version 6.x and concrete5, version 7.4"

**Comment by MeyerJL** [comment]
I like the idea of concrete-legacy a lot.

I do wonder about the timing a bit though. Movement on the [Composer.json](https://github.com/concrete5/concrete5-5.7.0/issues/360) issue for 5.7 has been sort of stagnant but it sure would be a pain to move to concrete5/concrete5 and 6 months later be working in concrete5/core. I got the impression that the composer.json stuff wasn't really a priority, I just fear that moving too soon would make it that much more of a struggle to get implemented with having to battle another repo move.

**Comment by mlocati** [comment]
+1 for the concrete-legacy

BTW, before switching the names please let me know (__it's very important__): I need to update the stuff that fetches the translations from Transifex. Otherwise we risk to throw away thousands of translations.

**Comment by KorvinSzanto** [comment]
@MeyerJL if anything we would keep `concrete5/concrete5` as the controllers and views and attributes and whatever else and move just the src directory to something like `concrete5/core` so I wouldn't worry about this causing any difficulty with that.

**Comment by MeyerJL** [comment]
Ah gotcha, reading a little closer I think that lines up with the spirit of that request, so you're right that's a non issue.

Also, fwiw github does have [repository redirects](https://github.com/blog/1508-repository-redirects-are-here) so I think the only one's who will really be impacted are those using the legacy version of concrete5.

**Comment by mkly** [comment]
Obligatory +1

**Comment by KorvinSzanto** [comment]
@Remo do you have any thoughts on this?

**Comment by Remo** [comment]
I'm all for it, just make sure it's well coordinated with all the transifex interfaces we have.

**Comment by KorvinSzanto** [comment]
@mlocati I believe we're gearing up to start doing this some time soon, would you be available over google chat?

**Comment by mlocati** [comment]
Sure! My gmail address is the same as my username @gmail.com

**Comment by aembler** [comment]
This is done! Travis should be working now...it's working for 5.7 but I think it's failing for 5.6 (though I don't know if enough to know if that's normal for where the build is right now.)

Now we can re-enable translations, make sure various composer installations work, etc.. 

Thanks Remo and everybody!

**Comment by Remo** [comment]
@aembler @mlocati did you update transifex? I'm getting error mails from them..

**Comment by mlocati** [comment]
@Remo Yesterday I removed the automatic update URLs from Transifex (me too I received those error emails but as you can read there the fetch urls are empty) and disabled the scripts on your server.
Today I'll update the scripts and re-enable everything.

**Comment by Remo** [comment]
okay, thanks! I was confused because it said unknown url type.

**Comment by mlocati** [comment]
Transifex-related stuff is running fine. All systems go!

**Comment by mlocati** [comment]
> okay, thanks! I was confused because it said unknown url type.

Me too! Receiving this kind of email is quite confusing!
```text
Hi Michele Locati,
We have not been able to update the source file for the resource concrete5 development 5.7.x of
the project concrete5.

The URL we used to update the source file from was .

The exact error we encountered was:

unknown url type:

--
The Transifex Robot

```

**Comment by aembler** [comment]
Thanks guys!

**Comment by mlocati** [comment]
> This is done! Travis should be working now...it's working for 5.7 but I think it's failing for 5.6 (though I don't know if enough to know if that's normal for where the build is right now.)

@aembler Yes, the tests were failing even [before the name changes](https://travis-ci.org/concrete5/concrete5-legacy/builds)
