### ISSUE TITLE
Moving to php 5.6 -> Object of class BlockRecord could not be converted to string

### ISSUE THREAD

**Issue by sylbal** [concrete5/concrete5-legacy#1915]
Hi, 

I'm using C5 5.6.0.2 on a VPS (Debian)

Moving my server from php-5.4 (5.4.41) to php-5.6 (5.6.9) leads the whole site to display a blank page with the error:

`PHP Catchable fatal error:  Object of class BlockRecord could not be converted to string in /var/www/concrete5.6.0.2/concrete/libraries/3rdparty/Zend/Cache/Core.php on line 361`

The post http://www.concrete5.org/community/forums/block_requests/web-page-fail-to-start-due-a-catcable-error/ gives a workaround but I did not found a real solution.

When commenting the line 361, the site seems ok and functionnal but in Edit mode, I have warnings in the log and the top bar does not display the icon for dashboard/edit, ...

`PHP Warning:  unserialize() expects parameter 1 to be string, array given in /var/www/concrete5.6.0.2/concrete/libraries/3rdparty/Zend/Locale/Data.php on line 325, referer: `

The only way to edit a page is now to call the /dashboard url, unset the cache, edit the page, then set back the cache on.

Any idea to fix this ?

**Comment by Remo** [comment]
sorry, we don't support such old versions anymore. Please update your concrete5 version first, thanks!
