### ISSUE TITLE
concrete 5.6.3.5b1 available here

### ISSUE THREAD

**Issue by mlocati** [concrete5/concrete5-legacy#1952]
As many people are looking for the very latest version of concrete5 (5.6.3.5b1), here it is:

[concrete5.6.3.5b1.zip](https://github.com/concrete5/concrete5-legacy/files/1048593/concrete5.6.3.5b1.zip)

Language files can be downloaded from https://translate.concrete5.org/translate/package/concrete5/dev-5.6 (the .mo files must be saved as `/languages/<LanguageCode>/LC_MESSAGES/messages.mo`)

**Comment by JohntheFish** [comment]
Good to see 5.6 maintenance continuing.
Are there any release notes for what has changed?

**Comment by mlocati** [comment]
I only answered to a request of a friend of mine :wink:.
I guess the best changelog we have for the 5.6 series is this one: https://github.com/concrete5/concrete5-legacy/compare/5.6.3.4...master

**Comment by hissy** [comment]
Let's release 5.6.3.5rc1

**Comment by a3020** [comment]
I guess this issue can be closed since 5.6.3.5 has been released? https://documentation.concrete5.org/developers/background/version-history/5635
http://www.concrete5.org/download

**Comment by mlocati** [comment]
:+1:
