### ISSUE TITLE
PHP Warning:  usort() expects parameter 2 to be a valid callback

### ISSUE THREAD

**Issue by weyboat** [concrete5/concrete5-legacy#1964]
I get this in the PHP_error log file when deleting the files in Trash folder.
The full PHP warning is..

PHP Warning:  usort() expects parameter 2 to be a valid callback, non-static method Page::queueForDeletionSort() should not be called statically in concrete\core\models\page.php on line 671

The files are successfully deleted despite the warning.
I am using PHP Version 7.1.9

**Comment by mlocati** [comment]
#1965 should fix these warnings.
