### ISSUE TITLE
PHP 7.2 Warnings 

### ISSUE THREAD

**Issue by weyboat** [concrete5/concrete5-legacy#1968]
In concrete/helpers/concrete/dashboard.php file PHP 7.2 throws three warnings..
Line 405 - ENABLE_INTELLIGENT_SEARCH_HELP 
Line 413 - ENABLE_INTELLIGENT_SEARCH_MARKETPLACE
Line 525 - ENABLE_MARKETPLACE_SUPPORT
These text strings need to be wrapped in single quotation marks to avoid the warnings.

**Comment by mlocati** [comment]
These are constants (so they must not be enclosed in quotes) that are defined in the [`concrete/config/app.php`](https://github.com/concrete5/concrete5-legacy/blob/master/web/concrete/config/app.php) file.
This file is not executed (so, these constants are not defined) only if the `$config_check_failed` global variable is set to false, and this case should occur only if concrete5 is not installed (see the [`concrete/startup/config_check.php`](https://github.com/concrete5/concrete5-legacy/blob/master/web/concrete/startup/config_check.php) file).

**Comment by weyboat** [comment]
Here are the warnings found in the PHP Error log..
[28-Dec-2017 10:01:20 UTC] PHP Warning:  Use of undefined constant ENABLE_INTELLIGENT_SEARCH_HELP - assumed 'ENABLE_INTELLIGENT_SEARCH_HELP' (this will throw an Error in a future version of PHP) in H:\wamp\www\newsite\concrete\helpers\concrete\dashboard.php on line 405
[28-Dec-2017 10:01:20 UTC] PHP Warning:  Use of undefined constant ENABLE_INTELLIGENT_SEARCH_MARKETPLACE - assumed 'ENABLE_INTELLIGENT_SEARCH_MARKETPLACE' (this will throw an Error in a future version of PHP) in H:\wamp\www\newsite\concrete\helpers\concrete\dashboard.php on line 413
[28-Dec-2017 10:01:20 UTC] PHP Warning:  Use of undefined constant ENABLE_MARKETPLACE_SUPPORT - assumed 'ENABLE_MARKETPLACE_SUPPORT' (this will throw an Error in a future version of PHP) in H:\wamp\www\newsite\concrete\helpers\concrete\dashboard.php on line 525

So, would you say that PHP 7.2 has a bug?

**Comment by mlocati** [comment]
> So, would you say that PHP 7.2 has a bug?

No, I'm saying that I don't understand why you have those undefined constants.

**Comment by weyboat** [comment]
Well this is odd..
From a fresh install of 5.6.4.0 on completion of the install I am auto signed into the site..
I hover my cursor over the Dashboard link at the top of the page and I see the warning displayed in the popup.
I check the PHP error log files and see those three warnings as per my previous post.
If I sign out of the site and then sign back in again and hover my cursor over the Dashboard link, the warning does not appear in the popup!
Also, the warnings in the PHP error log are not repeated!
Any Idea what is happening here?

**Comment by mlocati** [comment]
> Any Idea what is happening here?

Yes: the result of the `getDashboardAndSearchMenus` method (where the affected lines are executed) is stored in a cache. So, next calls to that method in the same session won't cause the warnings to be thrown.

**Comment by mlocati** [comment]
I may have understood why we have those warnings: see #1969

**Comment by weyboat** [comment]
Yes Mike your modifications to the concrete/helpers/concrete/interface.php file has fixed this issue.
I just tested this in another install and I no longer see any warnings.
Well done.

**Comment by mlocati** [comment]
Thanks for checking!
