### ISSUE TITLE
File Manager Fails to create Thumbnails with PHP 7.2

### ISSUE THREAD

**Issue by weyboat** [concrete5/concrete5-legacy#1972]
To reproduce this error..
Install a fresh copy of concrete 5.6.4.0 with no addons and no content.
Go to the file manager and upload an image (jpg or png) the upload hangs (see image 1)

![manager1](https://user-images.githubusercontent.com/24839536/34561758-76d0d7fe-f143-11e7-82ef-68b0e24d91ee.jpg)

Refresh the browser or leave the page and revisit it to find the image thumbnail was not created and no 'height' set in the attributes. (see image 2)

![manager2](https://user-images.githubusercontent.com/24839536/34561759-76e5bc50-f143-11e7-80d5-2d5afac05ab3.jpg)

Try to Rescan the image and the spinner runs continually with Rescan failing to complete.
Upload a file that is not an image (pdf for instance) and it completes successfully (see image 3)

![manager3](https://user-images.githubusercontent.com/24839536/34561760-76fd5ec8-f143-11e7-8554-e02f1a333906.jpg)

There are no errors in the php log file?
The Apache error log does show errors and a sample is..

`[Thu Jan 04 10:42:08.694084 2018] [mpm_winnt:notice] [pid 11240:tid 716] AH00428: Parent: child process 6332 exited with status 255 -- Restarting.
[Thu Jan 04 10:42:08.912877 2018] [mpm_winnt:notice] [pid 11240:tid 716] AH00455: Apache/2.4.29 (Win64) PHP/7.2.0 configured -- resuming normal operations
[Thu Jan 04 10:42:08.912877 2018] [mpm_winnt:notice] [pid 11240:tid 716] AH00456: Apache Lounge VC15 Server built: Oct 20 2017 12:12:11
[Thu Jan 04 10:42:08.912877 2018] [core:notice] [pid 11240:tid 716] AH00094: Command line: 'h:\\wamp\\bin\\apache\\apache2.4.29\\bin\\httpd.exe -d H:/wamp/bin/apache/apache2.4.29'
[Thu Jan 04 10:42:08.928511 2018] [mpm_winnt:notice] [pid 11240:tid 716] AH00418: Parent: Created child process 6392
[Thu Jan 04 10:42:09.116005 2018] [mpm_winnt:notice] [pid 6392:tid 660] AH00354: Child: Starting 64 worker threads.`

The browser Debugger shows the following error.

`about:neterror?e=netReset&u=http%3A//newsite/index.php/tools/required/files/importers/single&c=UTF-8&f=regular&d=The%20connection%20to%20the%20server%20was%20reset%20while%20the%20page%20was%20loading.
`
This occurs on a live server and my development box.
Switching PHP version from PHP 7.2 to PHP 7.1 and the errors are gone.

**Comment by weyboat** [comment]
Incidentally, Although the thumbnails do not get created, the image itself can be used in the site image and content blocks..

**Comment by Remo** [comment]
it's even better for me, the last thing I see is `PHP Notice:  Unknown: file created in the system's temporary directory in Unknown on line 0` and then PHP crashes. Tested with PHP 7.2.1.

**Comment by weyboat** [comment]
Ah, at least its not my dev box setup at fault.
Having said that I have tested it on a live server with the same result.

**Comment by mlocati** [comment]
I analyzed what's happening, and the failing line is [this one](https://github.com/concrete5/concrete5-legacy/blob/4906ec076751a50ad8e4b41cf589406020c1411b/web/concrete/libraries/3rdparty/adodb/drivers/adodb-mysqli.inc.php#L1035), where PHP dies because of what's seems a PHP bug to me.

**Comment by Remo** [comment]
I think it doesn't end there, this needs to be replaced too: https://github.com/concrete5/concrete5-legacy/blob/4906ec076751a50ad8e4b41cf589406020c1411b/web/concrete/libraries/3rdparty/adodb/adodb-datadict.inc.php#L523

There's a patch for this though https://github.com/ADOdb/ADOdb/commit/d9cc6c66ec08e5a517f8fa4503345ead992e2a62

The line you pointed out still looks the same.

I guess we aren't quite ready for PHP 7.2 or PHP 7.2 isn't ready for us ;-)

**Comment by weyboat** [comment]
Ha Ha, were well ahead of the game!

**Comment by Remo** [comment]
Here's a PR that should take care of the `each` problem. It updates adodb to an unreleased version though..
https://github.com/concrete5/concrete5-legacy/pull/1975

**Comment by mlocati** [comment]
> I think it doesn't end there, this needs to be replaced too:

Yes, the `each` calls throw a warnings, but in my case the whole PHP process crashes when PHP calls `mysqli_fetch_array` and Windows Error Reporting creates a dump. I asked a colleague of mine (expert in debugging) to inspect this dump.

**Comment by Remo** [comment]
Cool, maybe we have to file something here http://bugs.php.net/
PHP 7.2 crashes for me too, I guess in the same line, but I didn't analyse it.

**Comment by hutbert** [comment]
php7.2 crashes for me as well.  After a bunch of digging I was able to consistently fix the issue by adjusting a switch statement in the adodb library. It feels like a php7.2 bug to me as I can see no reason why this would work. 

See https://github.com/concrete5/concrete5-legacy/compare/master...hutman:issue_1972 for the change I made. I'd be super curious to hear if anyone can see what would make that work properly.

**Comment by weyboat** [comment]
I tried replacing the adodb library to the v5.21.0-dev version but that made no difference.
I just tried your hack of the adobd-mysqli.inc.php file and this did indeed fix the issue.
Thanks @hutbert for tracking this down..

**Comment by weyboat** [comment]
Further testing this and unfortunately this hack prevents a fresh install of 5.6.4.0, it throws two errors.
The first one is easily fixable as the solution is given in the error message.. 
PHP Warning:  Use of undefined constant ENABLE_LOG_ERRORS - assumed 'ENABLE_LOG_ERRORS' (this will throw an Error in a future version of PHP) in \xxxxxxx\concrete\startup\exceptions.php on line 5

The second error message is..
PHP Fatal error:  Uncaught Error: Call to a member function MetaTables() on boolean in \xxxxxxxx\concrete\startup\exceptions.php:7

**Comment by mlocati** [comment]
The original issue should be an opcache bug (I can't replicate the problem without opcache).
I submitted it: https://bugs.php.net/bug.php?id=76094

**Comment by weyboat** [comment]
I can confirm that with opcache disabled the problem does not occur as tested on my wamp box with PHP 7.2.3

**Comment by weyboat** [comment]
I just added my vote to the bug report at php.net

**Comment by weyboat** [comment]
Looks like a patch for this PHP bug has been written.
http://git.php.net/?p=php-src.git;a=commit;h=4758164ac5fd61be70d9366175b30df758ac8262

**Comment by mlocati** [comment]
It seems they [already fixed](https://bugs.php.net/bug.php?id=76094#1521083845) this bug. We just have to wait for PHP 7.2.4

**Comment by mlocati** [comment]
😆

**Comment by weyboat** [comment]
I noticed the PHP team have released PHP 7.2.4 so we can try it out now..

**Comment by weyboat** [comment]
This is odd, when the release candidate of 7.2.4 was made available I grabbed the new opcache dll file and replaced the one in my wamp php 7.2.3 extensions folder with the updated one and tested the file uploads and they worked - no errors.
Now I have installed the latest release of PHP 7.2.4 and the file uploads are broken again?

**Comment by weyboat** [comment]
7.2.4 didn’t fix the thumbnail issue for me, has it made a difference for anyone else ?

**Comment by weyboat** [comment]
The PHP team have released version 7.2.5 and I am happy to announce that this appears to have fixed the thumbnail error, at least it has fixed it for me in my 64 bit WAMP server running on Windows 10..

**Comment by weyboat** [comment]
@mlocati can you verify my findings on PHP 7.2.5 please before I close this issue

**Comment by mlocati** [comment]
The bug I filed (https://bugs.php.net/bug.php?id=76094) seems to have been fixed by PHP 7.2.5 (http://www.php.net/ChangeLog-7.php#7.2.5)

**Comment by weyboat** [comment]
Thanks for verifying that is now fixed, I will close this issue now.
