### ISSUE TITLE
Proforms Add On install error

### ISSUE THREAD

**Issue by justynpride** [concrete5/concrete5-legacy#1973]
I'm trying out v5.6.4 to see what issues any of my current add ons my encounter. Running on both PHP 5.6 and 7 I get the following error when trying to install Proforms. 

Fatal error: Call to undefined static method Concrete5_Model_AttributeKey::add() in /Applications/MAMP/htdocs/concrete5legacy/concrete/core/models/attribute/key.php on line 13

Unfortunately this add on is no longer supported by the developer, so I'm trying to work out what 'life span' my systems might have. I've had support from the C5 forums, but this Fatal errors appears to be a challenge.

**Comment by Remo** [comment]
Try calling `addAttributeKey` instead of `add`

**Comment by mlocati** [comment]
Try applying #1974

**Comment by justynpride** [comment]
Thanks @mlocati it now installs. Naturally I've now hit another load of errors. I'm feeling like this might not be worth it, as I don't want to have to attempt to update all the code in Proforms. 

Warning: Declaration of ProformsItemItemList::sortBy($key, $dir) should be compatible with Concrete5_Library_ItemList::sortBy($column, $direction = 'asc') in /Applications/MAMP/htdocs/legacyc5/packages/proforms/libraries/item_list_proforms_item.php on line 8

Warning: Declaration of ProformsItemList::get($itemsToGet = 0, $offset = 0) should be compatible with ProformsItemItemList::get($itemsToGet = 0, $offset = 0, $dbs = NULL) in /Applications/MAMP/htdocs/legacyc5/packages/proforms/models/proforms_item_list.php on line 14
ProForms

Warning: Cannot modify header information - headers already sent by (output started at /Applications/MAMP/htdocs/legacyc5/packages/proforms/libraries/item_list_proforms_item.php:8) in /Applications/MAMP/htdocs/legacyc5/concrete/core/libraries/view.php on line 648

An unexpected error occurred.
Using $this when not in object context

**Comment by Remo** [comment]
@justynpride there is some bad code in the add-on itself for sure. `ProformsItemItemList` is derived from `ProformsItemList`, but declares some methods different from their parent method. It's most likely easy to fix, but it's not something that's wrong in the core, it's the add-on.

**Comment by justynpride** [comment]
@Remo  Thanks for the confirmation. I thought it might be more of the add on now. I'll have one more look at it before shelving.

**Comment by Remo** [comment]
you basically just have to make sure that the methods with the same name have the same arguments. Add `, $dbs = NULL` to `ProformsItemList::get` should get rid of one warning. If you're desperate you can also hide all warnings, but don't tell anyone I've said that. I'm going to close this, the core should be fine now.

**Comment by mlocati** [comment]
Also note that argument names may be different: method just need to have the same number of arguments, types and default values.
So, for instance, I'd change `sortBy` method of `ProformsItemItemList` from
```php
function sortBy($key, $dir)
```
to
```php
function sortBy($key, $dir = 'asc')
```
so that it's compatible with `Concrete5_Library_ItemList::sortBy($column, $direction = 'asc')`

**Comment by justynpride** [comment]
@mlocati That is very helpful. Just one one error to sort now. You guys are amazing!
Using $this when not in object context

**Comment by mlocati** [comment]
> Using $this when not in object context

In order to fix this, we'd need to see the code...

**Comment by justynpride** [comment]
Very happy for that. I don't know if the below if helpful. There are a few pages that give the same error, but these are the files that I see relate:

**single_pages/proforms/dashboard/proforms/overview.php**
`<?php 
defined('C5_EXECUTE') or die(_("Access Denied."));
?>
    <?php   echo Loader::helper('concrete/dashboard')->getDashboardPaneHeaderWrapper(t('ProForms'), t('Search Proforms Item\'s on your site and perform bulk actions on them.'), false, false);?>
	<div class="ccm-pane-body">
	    <?php    Loader::packageElement('dashboard/proforms/search/dashboard', 'proforms')  ?>
	</div>
		
    <div class="ccm-pane-footer">

	</div>`

**controllers/proforms/dashboard/proforms/overview.php**
`<?php    
defined('C5_EXECUTE') or die(_("Access Denied."));

Loader::model('attribute/categories/proforms_item', 'proforms');
Loader::model('proforms_item_list', 'proforms');

class DashboardProformsOverviewController extends Controller {
	
	public $helpers = array('html','form');
	
	public function on_start() {
		$this->error = Loader::helper('validation/error');
		$this->addHeaderItem(Loader::helper('html')->javascript('jquery.dd.min.js','proforms'));
		$this->addHeaderItem(Loader::helper('html')->css('dd.css','proforms'));
		$this->addHeaderItem(Loader::helper('html')->javascript('jquery.js'));
		
		$html = Loader::helper('html');
		$uh = Loader::helper('concrete/urls');
		$pkg = Package::getByHandle('proforms');
		$this->addFooterItem($html->css('signature/jquery.signaturepad.css','proforms'));
		$this->addFooterItem($html->javascript('bootstrap.js'));
		$this->addFooterItem($html->javascript('json2.min.js','proforms'));
		$this->addFooterItem($html->javascript('jquery.signaturepad.js','proforms'));
		$this->addFooterItem('');
		$this->addFooterItem('');
		$this->addFooterItem('');
		$this->addHeaderItem('<script type="text/javascript">$(function() { ccm_setupAdvancedSearch(\'proforms-item\'); });</script>');
		$this->addHeaderItem('<script type="text/javascript" src="'.$uh->getPackageURL($pkg).'/js/proforms_item.ui.js"></script>');
	}
	
	public function view(){
	
	}
}`

**proforms/elements/dashboard/proforms/search/dashboard.php**
`<?php    defined('C5_EXECUTE') or die(_("Access Denied.")); ?> 
<style type="text/css">
.btn-large{width: 80%;}
.formsets a{color: black;}
.formsets hr{margin: 12px 0;}
.formsets .badge{float:right;}
</style>
    <?php 
    $category = AttributeKeyCategory::getByHandle('proforms_item');
	$sel = array('0' => t('** None'));
	$sets = $category->getAttributeSets();
	foreach($sets as $as) {
	    $ProformsItemList = new ProformsItemList();
	    $ProformsItemList->filterByAttributeSet($as->getAttributeSetID());
	    $items = $ProformsItemList->get();
	    $count = count($items);
		?>
		<div class="span3 well formsets">
            <a href="<?php   echo $this->url('/dashboard/proforms/search/')?>?asID=<?php echo $as->getAttributeSetID()?>">
                <h4><span class="badge badge-inverse"><?php echo $count?></span> <?php echo $as->getAttributeSetName()?></h4>
                <br/>
                <hr/>
                <a href="<?php   echo $this->url('/dashboard/proforms/search/')?>?asID=<?php echo $as->getAttributeSetID()?>"><i class="icon icon-tasks"></i> &nbsp;<?php echo t('View Submissions')?></a>
                <hr/>
                <a href="<?php   echo $this->url('/dashboard/proforms/editor/')?><?php echo $as->getAttributeSetID()?>/" class=""><i class="icon icon-edit"></i> &nbsp;<?php echo t('Edit Form')?></a>
                <hr/>
                <a href="<?php   echo BASE_URL.DIR_REL?>/index.php/tools/packages/proforms/proforms/search_results_export.php?asID=<?php echo $as->getAttributeSetID()?>" class=""><i class="icon icon-share-alt"></i> &nbsp;<?php echo t('Export')?></a>
            </a>
        </div>
        <?php 
	}
    ?>
    <br style="clear: both;"/>
`

**Comment by mlocati** [comment]
Could you enclose the PHP / HTML code in three backticks ` ? That way the code should be more readable.
Furthermore, I think that writing 3rd party code on a publicly accessible page (like this one) isn't legally correct. Could you could send me a PM in [Slack](https://concrete5.slack.com)?

**Comment by justynpride** [comment]
Will do. Sorry for the school boy error.

**Comment by mlocati** [comment]
The `Using $this when not in object context` error **should** be fixed by changing this line in the `getByID()` method of `ProformsItemAttributeKey` (file `/packages/proforms/models/attribute/categories/proforms_item.php`):
from: `$cnt->setAttributeKey($this);`
to: `$cnt->setAttributeKey($ak);`

**Comment by justynpride** [comment]
It works! Huge thank you on this. At least I can now look at how well the add-on and the custom applications built from it operate.
