### ISSUE TITLE
XSS vulnerability

### ISSUE THREAD

**Issue by jordanlev** [concrete5/concrete5-legacy#1976]
Hi, I've discovered an XSS vulnerability and emailed you guys about it 2 months ago but never heard a response (also don't see any recent commits that address it). How would you like me to report this to you? Should I re-send the email (and to which address -- I originally sent it to security@concrete5.org, back on December 19th), or post the details here on github?

Thanks,
Jordan

**Comment by jordanlev** [comment]
Oops, accidentally posted this to the legacy repo instead of the new one.

**Comment by mkly** [comment]
https://hackerone.com/concrete5
