### ISSUE TITLE
Problem with MySQL 8

### ISSUE THREAD

**Issue by Remo** [concrete5/concrete5-legacy#1980]
Can't install it on MySQL 8, getting this error

```
Unable to install database: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'Groups ( gID INTEGER(10) UNSIGNED NOT NULL AUTO_INCREMENT, ' at line 1
```

**Comment by JohntheFish** [comment]
There was a fix on v8 for this. https://github.com/concrete5/concrete5/pull/6753

**Comment by jbender0** [comment]
My hosting company found a solution for the compatibility issue between Concrete 5.6 and MySQL8. I explained the full solution in this forum post - https://forums.concretecms.org/t/concrete-5-6-and-mysql8-solved/7024

**Comment by ktarasov** [comment]
> My hosting company found a solution for the compatibility issue between Concrete 5.6 and MySQL8. I explained the full solution in this forum post - https://forums.concretecms.org/t/concrete-5-6-and-mysql8-solved/7024

The replacement code specified in the post may cause the CMS to malfunction, since it does not replace only where it is needed.
