### ISSUE TITLE
MySQL error on file manager

### ISSUE THREAD

**Issue by prpdesigns** [concrete5/concrete5-legacy#1984]
In File Manager, this error appears:

`mysqli error: [3065: Expression #1 of ORDER BY clause is not in SELECT list, references column 'argomedo_propieda.f.fDateAdded' which is not in SELECT list; this is incompatible with DISTINCT] in EXECUTE("SELECT DISTINCT f.fID, u.uName as fvAuthorName FROM Files f INNER JOIN FileVersions fv ON f.fID = fv.fID LEFT JOIN Users u on u.uID = fv.fvAuthorUID left join FileSearchIndexAttributes on (fv.fID = FileSearchIndexAttributes.fID) where 1=1 and fvIsApproved = '1' order by fDateAdded desc limit 0,10 ")`

**Comment by mlocati** [comment]
Which concrete5 version are you using?

**Comment by prpdesigns** [comment]
First error popped in 5.6.3.4, updated to 5.6.3.5 and error persists

**Comment by mlocati** [comment]
Try using the very latest version, available at https://github.com/concrete5/concrete5-legacy/archive/master.zip
