### ISSUE TITLE
Chrome 83 breaks page properties saving

### ISSUE THREAD

**Issue by prpdesigns** [concrete5/concrete5-legacy#2000]
OS: Windows 10 and Kubuntu linux.

Chrome version: 83.0.4103.61

Opening page properties, trying to save leads to a blank alert and page properties will not be saved.

Mozilla Firefox and Opera works as intended.

![Untitled-1](https://user-images.githubusercontent.com/6282732/82532796-0f7f3b80-9b10-11ea-9323-82d980653a05.jpg)

**Comment by prpdesigns** [comment]
Also, Content Block doesn't save

**Comment by hissy** [comment]
It might be the same issue https://github.com/concrete5/concrete5/pull/8664

**Comment by pripboy** [comment]
> It might be the same issue [concrete5/concrete5#8664](https://github.com/concrete5/concrete5/pull/8664)

Yes, same fix on concrete/js/jquery.form.js

**Comment by Remo** [comment]
Created a PR https://github.com/concrete5/concrete5-legacy/pull/2001
I will monitor this PR https://github.com/jquery-form/form/pull/572 by Korvin to see if anyone on jquery-form has a reason not to fix it like that.

**Comment by FortyNinjaFISH** [comment]
Latest Google Chrome update (v83.0.4103.97) appears to have solved this issue for me.
