### ISSUE TITLE
MYSQL 8 Error 

### ISSUE THREAD

**Issue by ConcreteOwl** [concrete5/concrete5-legacy#2008]
MYSQL 8 causes errors when loading a 5.6.4.0 site with the following message...
###
mysqli error: [1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'Groups where gID = '1'' at line 1] in EXECUTE("select * from Groups where gID = '1'")
###
I have successfully 'fixed' this by editing the concrete/core/models/groups.php file to add backticks to the word Groups on line 14, 91 and 107

**Comment by Remo** [comment]
This is already fixed in this git repo, but since there won't be any releases of 5.6 anymore, you'll have to take the code from here. I doubt there is enough demand, but if I am mistaken, we could ask Andrew to release 5.6.4.1

**Comment by ConcreteOwl** [comment]
Okay, Thank you Remo
